Add provisioning intro
wso2/docs-is pull request #1984
Opened 2020-08-25 09:05 UTC by sherenewso2

2020-08-25 09:19 UTC, isharak commented on en/docs/concepts/identity-provisioning-intro.md
> +Most enterprise solutions adopt products and services from multiple cloud providers to accomplish various business requirements. This makes it insufficient to maintain user identities only in a corpo
Let's use "corporate user store (corporate LDAP)"

2020-08-25 09:22 UTC, isharak commented on en/docs/concepts/identity-provisioning-intro.md
> +Most enterprise solutions adopt products and services from multiple cloud providers to accomplish various business requirements. This makes it insufficient to maintain user identities only in a corpo
WE have to say that "due to this reason we have to maintain user information in multiple places"

2020-08-25 09:23 UTC, isharak commented on en/docs/concepts/identity-provisioning-intro.md
> +Most enterprise solutions adopt products and services from multiple cloud providers to accomplish various business requirements. This makes it insufficient to maintain user identities only in a corpo
not only SaaS providers maybe we can say "across multiple systems"

2020-08-25 09:23 UTC, isharak commented on en/docs/concepts/identity-provisioning-intro.md
> +For instance, if an employee leaves an organization, their user account may need to be removed and permissions may need to be revoked from multiple applications within the organization. However, it t
this does not connect this para to previous one

2020-08-25 09:24 UTC, isharak commented on en/docs/concepts/identity-provisioning-intro.md
> +For instance, if an employee leaves an organization, their user account may need to be removed and permissions may need to be revoked from multiple applications within the organization. However, it t
we can further say that "This is a main privacy regulatory requirement"

2020-08-25 09:26 UTC, isharak commented on en/docs/concepts/identity-provisioning-intro.md
> +After a user has been provisioned, WSO2 IS can also help maintain the user's updated information across all configured applications. For example, to update a user attribute such as telephone number,
connected applications ?

2020-08-25 09:27 UTC, isharak commented on en/docs/concepts/identity-provisioning-intro.md
> +Provisioning is bi-directional, hence there are two main types.
bi-directional provides a different meaning, it seems in the same connection we do provisioning in both sides.
maybe we can say two types

2020-08-25 10:53 UTC, gomathyk requested changes

2020-08-25 10:53 UTC, gomathyk commented on en/docs/concepts/identity-provisioning-intro.md
> +Identity provisioning is the process of creating, updating, managing, and removing digital identities in a system or application. The main purpose of identity provisioning using an identity managemen
Shall we divide the second sentence? It seems a bit long.

2020-08-25 10:53 UTC, gomathyk commented on en/docs/concepts/identity-provisioning-intro.md
> +Most enterprise solutions adopt products and services from multiple cloud or on premise providers, to accomplish various business requirements. This means user identity information must be maintained
Please change "userstore" to be one word for consistency wherever applicable.

2020-08-27 07:57 UTC, gomathyk approved these changes

2020-08-27 08:20 UTC, merged