Update Dev Mode instructions, add Dark mode preference
wso2/docs-is pull request #2498
Opened 2021-03-12 15:40 UTC by ghost

## Purpose
> When trying to run locally the instructions left out some important steps. I found the feature in the mkdocs-material theme that allows the page to render based on the system "dark/light" preference

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-03-18 19:55 UTC, vordimous commented
This is my PR. I am consolidating my accounts and I should have closed before deleting the old account.

2021-04-21 05:22 UTC, gomathyk requested changes

2021-04-21 05:22 UTC, gomathyk commented on README.md
> +1. Ensure Python and Pip are installed
```suggestion
1. Ensure that Python and Pip are installed.
```

2021-04-21 05:22 UTC, gomathyk commented on README.md
>  1. Clone repo
Give the link to the repo.

2021-04-21 05:22 UTC, gomathyk commented on README.md
> +1. Install mkdocs cli tool `pip install mkdocs`
```suggestion
1. Install the mkdocs cli tool using the command, `pip install mkdocs`.
```

2021-04-21 05:22 UTC, gomathyk commented on README.md
> +1. Install the material theme `pip install mkdocs-material`
```suggestion
1. Install the material theme using the command, `pip install mkdocs-material`.
```

2021-04-21 05:22 UTC, gomathyk commented on README.md
> +1. Install the markdown extension `pip install markdown-include`
```suggestion
1. Install the markdown extension using the command, `pip install markdown-include`.
```

2021-04-21 05:22 UTC, gomathyk commented on README.md
> +1. Run `mkdocs serve` command in `<Lang folder>`. E.g. `cd en && mkdocs serve`
```suggestion
1. Run `mkdocs serve` in `<Lang folder>`, e.g., `cd en && mkdocs serve`
```

2021-04-21 05:22 UTC, gomathyk commented on README.md
> +1. Run `mkdocs serve` command in `<Lang folder>`. E.g. `cd en && mkdocs serve`
Give the folder path.

2021-04-21 05:24 UTC, madurangasiriwardena commented
@vordimous can you please check the above comments?

2021-04-21 12:49 UTC, gomathyk approved these changes

2021-04-21 14:44 UTC, vordimous commented
@gomathyk @madurangasiriwardena I have addressed the comments above.

2021-04-21 17:52 UTC, merged