New landing page
wso2/docs-is pull request #2613
Opened 2021-05-21 10:13 UTC by DonOmalVindula

## Purpose
 Implements a new landing page to on-prem documentation site.

## Goals
This PR replaces the existing landing page of the on-prem documentation site with a new design proposed in the issue mentioned below.

Resolves https://github.com/wso2/product-is/issues/11551

## Approach

1. A new template `landing-page.html` was created in `en/theme/material/templates/` as the base layout of the landing page.

2. `en/docs/index.md` file of the project was completely changed to accommodate the new design for the landing page.

3. In `en/theme/material/partials` directory, `header.html`, `tabs-item.html` and `footer.html` was changed to align the header and footer UI with the new design.

4. Custom files `search.html` and `source.html` were used  to customize the site search UI and Github repo links.

5. Added 9 new icons to the project in `en/docs/assets/img/icons/` from the new design

6. `en/docs/assets/css/theme.css` file was changed to accommodate new UI changes and mobile responsiveness.

![Implmented Landing Page](https://user-images.githubusercontent.com/42619922/119121142-b14ea680-ba4a-11eb-9f25-2520c27ca5f7.png)

2021-05-21 10:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-is?pullRequest=2613) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-is?pullRequest=2613) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-is?pullRequest=2613) it.</sub>

2021-05-21 10:41 UTC, mefarazath commented on en/docs/assets/css/theme.css
> +}
```suggestion
}

```

2021-05-24 05:11 UTC, NipuniBhagya requested changes

2021-05-24 05:11 UTC, NipuniBhagya commented on en/docs/assets/css/theme.css
> +    -webkit-box-shadow: 1px 6px 18px 4px rgba(77,77,77,0.15);
Isn't setting the box-shadow attribute enough?

2021-05-24 05:11 UTC, NipuniBhagya commented on en/docs/assets/css/theme.css
> +    }
Please fix the formatting here.

2021-05-24 05:11 UTC, NipuniBhagya commented on en/docs/assets/img/icons/landing-page/admin.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="23.999" viewBox="0 0 24 23.999">
Add WSO2 license headers to all the newly added files.

2021-05-24 05:11 UTC, NipuniBhagya commented on en/docs/index.md
> +                           <p class="scenario-card-text">Allow users to securely log in to multiple applications by providing their credentials just once.</p>
Please fix the formatting here.

2021-05-24 05:11 UTC, NipuniBhagya commented on en/theme/material/partials/search.html
> +</div>
Please add a new line here.

2021-05-24 05:11 UTC, NipuniBhagya commented on en/theme/material/partials/source.html
> +</a>
Add a new line here as well.

2021-05-24 05:11 UTC, NipuniBhagya commented on en/theme/material/templates/landing-page.html
> + * Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```suggestion
 * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

2021-05-24 05:11 UTC, NipuniBhagya commented on en/theme/material/templates/landing-page.html
> +			max-width: unset !important;
Please fix the formatting here.

2021-05-25 05:27 UTC, NipuniBhagya approved these changes

2021-05-25 05:29 UTC, merged