Update docs sidebar UI and other UI fixes
wso2/docs-is pull request #2644
Opened 2021-06-03 12:24 UTC by DonOmalVindula

## Purpose
Implements new sidebar UI for table of contents, left-side navbar and fixes numerous UI issues in on-prem docs site.

## Goals
This PR replaces the existing sidebar UIs of the on-prem documentation site with a newer design and fixes issues mentioned below.

Resolves https://github.com/wso2/product-is/issues/11782, https://github.com/wso2/product-is/issues/11785, https://github.com/wso2/product-is/issues/11808

## Approach
1. The left navigation sidebar UI was implemented by updating the `nav.html` and `nav-item.html` in `en/theme/material/partials/` directory.

2. The right side table of contents was implemented by updating the `toc.html` and `toc-item.html` in `en/theme/material/partials/` directory.

3.  Footer and header was changed to accommodate the new sidebars by altering files `footer.html`, `tabs.html` and `tabs-item.html` in `en/theme/material/partials/` directory.

4. Added a new icon (arrow_down.svg) for the left sidebar UI in `en/docs/assets/img/icons/` directory.

5. `en/docs/assets/css/theme.css`, `en/theme/material/templates/landing-page.html` and `en/docs/assets/css/theme.css` files were altered to fix UI issues in Mac systems and mobile views.

![image](https://user-images.githubusercontent.com/42619922/120643878-4ebac900-c494-11eb-8c04-d2d2cc66620d.png)

## Test environment
Tested with the following Mkdocs dependencies on Ubuntu 20.04.1
- mkdocs - 1.1.2
- mkdocs-material - 4.1.1
- mkdocs-material-extensions - 1.0.1
- pymdown-extensions - 5.0

2021-06-04 04:00 UTC, kanchanagodage commented on en/theme/material/partials/toc.html
> + * Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
2019 or 2021?

2021-06-04 04:02 UTC, kanchanagodage commented on en/theme/material/templates/landing-page.html
> +      }
Format the code with 4 space indentation

2021-06-04 09:56 UTC, NipuniBhagya requested changes

2021-06-04 09:56 UTC, NipuniBhagya commented on en/theme/material/templates/landing-page.html
> +		margin-right: 0;
Please fix the indentation here.

2021-06-04 09:56 UTC, NipuniBhagya commented on en/theme/material/partials/toc.html
> +<!--
If this file is from the material theme we can't add our license header. Please verify it.

2021-06-04 09:56 UTC, NipuniBhagya commented on en/docs/assets/img/icons/landing-page/arrow_down.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="18px" viewBox="0 0 24 24" width="18px" fill="#000000"><path d="M24 24H0V0h24v24z" fill="none" opacity=".87"/><path d="M16.59 8.59L12 13.17 7.41 8.59 6
Please format the SVG properly. Also please add an ID to it.

2021-06-07 09:51 UTC, NipuniBhagya commented on en/theme/material/templates/landing-page.html
> +{% endblock %}
Add a new line here.

2021-06-07 09:52 UTC, NipuniBhagya approved these changes

2021-06-07 11:13 UTC, merged