Update creating-users-using-the-ask-password-option.md
wso2/docs-is pull request #2667
Opened 2021-06-09 10:22 UTC by ChamathNS

## Purpose
$subject.
Update docs for the config introduced with https://github.com/wso2/carbon-identity-framework/pull/3559

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-06-09 11:03 UTC, gomathyk commented on en/docs/learn/creating-users-using-the-ask-password-option.md
> +    By default, WSO2 Identity Server would set a random value for the password if the **askPassword** claim is present in the request.
```suggestion
    By default, WSO2 Identity Server sets a random value for the password if the `askPassword` claim is present in the request. 
```

2021-06-16 06:45 UTC, gomathyk requested changes

2021-06-16 08:16 UTC, ChamathNS commented on en/docs/learn/creating-users-using-the-ask-password-option.md
> +``` toml
Addressed with 4c0475db280683386f925b7cb53f3302b331eba9.

2021-06-21 12:04 UTC, gomathyk approved these changes

2021-06-21 12:18 UTC, merged