Add recovery regex config to docs
wso2/docs-is pull request #2700
Opened 2021-07-28 13:48 UTC by ShanChathusanda93

## Purpose
> Added the missing configuration details

2021-07-28 13:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-is?pullRequest=2700) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-is?pullRequest=2700) before we can accept your contribution.<br/><hr/>**Shan Jayathilaka** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-is?pullRequest=2700) it.</sub>

2021-07-28 14:42 UTC, ChamathNS commented on en/docs/learn/password-recovery.md
> +   redirect URL that the user needs to be redirected.
Is this formatted correctly?

2021-07-28 14:42 UTC, ChamathNS approved these changes

2021-07-28 16:17 UTC, ShanChathusanda93 commented on en/docs/learn/password-recovery.md
> +   redirect URL that the user needs to be redirected.
Fixed

2021-07-28 16:45 UTC, ChamathNS commented on en/docs/learn/password-recovery.md
> +6. To allow the user's to redirect to a certain location after the password recovery request is completed, change the
```suggestion
6. To allow the users to be redirected to a certain location after the password recovery request is completed, change the
```

2021-07-28 16:46 UTC, ChamathNS commented on en/docs/learn/password-recovery.md
> +default configuration in **Recovery callback URL regex** into a specific regular expression which will match with the
```suggestion
default configuration in **Recovery callback URL regex** to a specific regular expression that will match the 
```

2021-07-29 03:42 UTC, gomathyk approved these changes

2021-07-29 03:43 UTC, gomathyk approved these changes

2021-07-29 03:43 UTC, gomathyk commented on en/docs/learn/password-recovery.md
> +redirect URL that the user needs to be redirected.
```suggestion
redirect URL that the user needs to be redirected to.
```

2021-07-29 08:49 UTC, gomathyk requested changes

2021-07-29 08:49 UTC, gomathyk commented on en/docs/administer/product-level-security-guidelines.md
> +In WSO2 Identity Server, you can specify regular expression patterns for callback URLs. In the recovery scenarios you have the capability to define
Shall we rephrase this as follows? 

For password recovery, you can define a regular expression to validate the callback URL. The default configuration allows any callback URL. Note that if you are using the recovery option, it is highly recommended to define the regular expression that validates and only allows access to specific callback URLs.

2021-07-29 08:49 UTC, gomathyk commented on en/docs/administer/product-level-security-guidelines.md
> +    For more informatoin, see <a href="../../learn/password-recovery">Password Recovery</a>.
```suggestion
    For more information, see [Password Recovery](../../../learn/password-recovery).
```

2021-07-29 08:49 UTC, gomathyk commented on en/docs/learn/password-recovery.md
> +6. To allow the users to be redirect to a certain location after the password recovery request is completed, change the
```suggestion
6. To allow the users to be redirected to a certain location after the password recovery request is complete, change the
```

2021-07-29 10:36 UTC, gomathyk approved these changes

2021-07-29 10:39 UTC, merged